application: first-vision-798
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:


- url: /css/font
  static_dir: website/css/font

- url: /css
  static_dir: website/css

- url: /js
  static_dir: website/js

- url: /images
  static_dir: website/images

- url: /short
  script: short.application
  
- url: /.*
  script: helloworld.application
